### ISSUE TITLE
Monorepoization tracking ticket

### ISSUE THREAD

**Issue by DRMacIver** [HypothesisWorks/hypothesis#1224]
#1209 was closed and I think legitimately - we've considered it and we're doing the thing. This ticket tracks progress towards a monorepo (maybe this should be a Project, but I'm not super convinced by the project workflow)

* [x] Refactor build scripts into something more manageable
* [x] Change our tagging scheme so that it makes sense across multiple languages. e.g. tags become hypothesis-python-X.Y.Z
* [x] Merge in hypothesis-ruby
* [ ] Merge in website
* [ ] Merge in hypothesis-java? Do we want to even do this? It's not really a maintained project. OTOH having it be the only thing outside the monorepo seems even weirder.

**Comment by DRMacIver** [comment]
> Ninja'd! Zac-HD there too.

OK. You should now have access. Let me know if it doesn't work.

**Comment by Zac-HD** [comment]
Yep, got access.  Now to fix it...

**Comment by Zac-HD** [comment]
Uh-oh: I can't see a way to make it install Hypothesis when setup.py is not in the repo root, and without installing Sphinx doesn't pick up on autodoc parts.  Like *all the strategies*.

**Comment by DRMacIver** [comment]
> Uh-oh: I can't see a way to make it install Hypothesis when setup.py is not in the repo root, and without installing Sphinx doesn't pick up on autodoc parts. Like all the strategies.

I've been thinking about moving us off RTD and onto hosting this on the website somehow... maybe this should be the impetus for that?

As a temporary hack, we could [configure a requirements file](https://docs.readthedocs.io/en/latest/yaml-config.html?highlight=setup.py#requirements-file) that installs the local package with a requirement of ./hypothesis-python.

**Comment by Zac-HD** [comment]
**Our CI is doomed.**

We're occasionally (daily?) getting long build queues with *one* project in the repo and no special events.  Once we have Rust, Ruby, Python, and ancillary files... business as usual will be a badly stretched system and sprints could take us out for a week.  It's also an awful experience for contributors :sob: 

Ideas:

- Ask Travis and Appveyor to sponsor us with an in-kind donation of CI resources - we're creating better customers and they could easily afford it.
- Seek fiscal or in-kind sponsorship elsewhere (corporate users?) to pay for the above.
- Use something like [beekeeper](https://github.com/pybee/beekeeper) to run auto-scaling private CI in the cloud.  Best capacity (most unshaven yaks!) and we'll probably need to go this way eventually, but there are still bills that *someone* has to pay.

**Comment by DRMacIver** [comment]
> We're occasionally (daily?) getting long build queues with one project in the repo and no special event

Note that it's no worse with a single repository than it is with multiple - the queue is organisation wide, it's just that you don't notice it because you're only working on the repo with slow tests!

I agree this is a problem though.

I'm keen to not start paying bills for our CI. :-) Sponsorship is probably a good idea though the last time I talked to Travis support about just how much resources we were using they went very quiet. I think we'd need to find the right person to talk to.

I do think there are a couple things we can do to fight back on these build times:

* I do think our CI times are just unneccessarily long and that "we're testing really thoroughly" is not actually a good reason for this. I'm not sure what the best route forward is, but I do think we should be able to fix this.
* Over time a lot of the slower tests can be moved into unit-ish tests of the Rust code. This should a) be a lot faster because Rust and b) Doesn't have the O(n) problem that having them for each language would.

**Comment by alexwlchan** [comment]
(Uh, expect all that to appear as a blog post soon. Consider that an early draft. 😛 )

**Comment by Zac-HD** [comment]
> Only run tests if you have relevant changes

`decisionmaker` looks good at the job level.  We could also go finer grained: have you seen [testmon](https://pypi.org/project/pytest-testmon/)?  Concept is basically that you can usefully intersect per-test line coverage with a diff range, and only run that subset of your tests... *and we don't have to build it ourselves*.

The other things sound good too :+1:

**Comment by DRMacIver** [comment]
> Only run tests if you have relevant changes

I think this is a good idea, but it's worth noting that our dependencies are somewhat rooted - e.g. a change to the rust core engine necessarily reruns basically every test (and typically all the slowest ones!). So although this will help I think there's still a need to get things faster for a full rebuild.

Also we want to do a full test before every release I think, so we probably can't just run them in cron.

> Consolidate tasks. At a large scale, the boot time of a Travis VM/container starts to add up. 

Yeah we should definitely do this one, and probably sooner rather than later.

> have you seen testmon? 
> Concept is basically that you can usefully intersect per-test line coverage with a diff range, and only run that subset of your tests...

I was actually one of the backers! I really like the idea but the last time I tried to use it with our test suite the slow down made it not worth it - we'd run say half as many tests but it took three times as long to run them. Maybe that's improved now!

> and we don't have to build it ourselves.

💔

**Comment by DRMacIver** [comment]
> Consolidate tasks. At a large scale, the boot time of a Travis VM/container starts to add up.

Proposed rule of thumb: We should be aiming to consolidate any build tasks (other than deploy) which currently take < 10 minutes.

**Comment by Zac-HD** [comment]
#1279 merged in `hypothesis-ruby`.  Should we...

- Check the box above, or is there more to do?
- Tag this repo `ruby` as well as `python`?
- Transfer over any open issues for Ruby?
- Lock issues on the old repo, or even remove it?

**Comment by Zac-HD** [comment]
Closing this as basically finished and *definitely* inactive.  If we want to merge the website in too, we should open a new issue just for that.
