### ISSUE TITLE
Hypothesis v4: scheduled for early 2019

### ISSUE THREAD

**Issue by Zac-HD** [HypothesisWorks/hypothesis#1696]
Like the elusive "Python 4", Hypothesis 4.0 will not be an exciting upgrade or include any new features.  

**The only change will be removing (most) deprecated functionality.**

However, even deprecated functionality will be kept if it was an officially supported way to do something within six months of the final release date, to make migration as easy as possible.  Weird accidental edge cases deprecated more recently may be removed anyway, at the maintainer's discretion.

Noting that it's been a while since we tried this in #1134 and #1156 (under different constraints), we are basically doing this from scratch.  Here's a first attempt at a checklist:

- [x] Remove unused exception types decf643a41dd53aad7558ff747a5d3a0face7d1e
- [x] Remove Faker extra, tests, docs, setuptools metadata, CI and tox jobs, isort entry, tests README entry.  Consider cherry-picking.
- [x] Remove datetime extra, tests, docs, setuptools metadata, tests README entry
- [x] Remove unused HealthCheck values
- [x] Remove all deprecated settings.  Clean up related now-needless code in settings initialisation and the database module.  Check docs for mentions of those settings, environment variables, etc.
- [x] Remove SQLite example database
- [x] Remove `streaming` strategy, `__all__` entry, all imports, tests, class in searchstrategy/types.py, hypothesis.types.Stream, tests for Stream.  Grep for `streaming|Stream` to check.
- [x] Remove `choices` strategy, `__all__` entry, tests, references in test_type_lookup blacklist and check_sample deprecation/error message.  Grep for `choices` to check.
- [x] Remove all deprecated arguments to strategies
- [x] Turn all uses of `note_deprecation` into an error, except for recent deprecations as noted above.

And ensure that all tests and linters pass before and after each of these changes, so they remain mostly atomic and can easily be rebased and/or cherry-picked if needed later.

Please comment with anything that I've missed!

**Comment by alexwlchan** [comment]
> Turn all uses of note_deprecation into an error. Add a required since= argument to the retained uses to track this in future. Use this to implement an "incentivising slowdown" based on length of deprecation.

We don't have to wait for v4 for this; at least not the first bit.

What did you envision putting in the `since` argument – a date? A version number?

**Comment by Zac-HD** [comment]
Moved to #1697; we should do at least most of that before v4.

**Comment by Zac-HD** [comment]
Based on experience from last time we tried this, and from trying to rebase and cherry-pick content from that branch, I have a few opinions about how to make this easier.  They boil down to: go fast and avoid merging non-urgent changes, ensure each change (e.g. most dot-points above) is a single commit, and use the usual PR process instead of a long-lived branch.  Thoughts?

Before starting I'll also try to rearrange the items so we can avoid editing anything which will be deleted in a later commit.  That should also ease rebasing or cherry-picking later :smile:

**Comment by DRMacIver** [comment]
So here's a possibly silly idea: Can we make it so that the only code change for 4.0 is a version bump? If we make it so that everything that is deprecated automatically turns into an error when the version is bumped, we can then do cleanup incrementally after 4.0 is released with a series of patches removing those errors, and that removes a lot of the coordination difficulty.

**Comment by alexwlchan** [comment]
> Can we make it so that the only code change for 4.0 is a version bump? If we make it so that everything that is deprecated automatically turns into an error when the version is bumped, we can then do cleanup incrementally after 4.0 is released with a series of patches removing those errors, and that removes a lot of the coordination difficulty.

I'd been idly wondering that.

Like you I'm not super keen on sleep incentives in #1697, but once we have that back-dated info, we can modify `note_deprecation` to error out anything deprecated before a certain date. Not all of it can go – I suspect, for example, the deprecated exception types won’t be caught by that – but you could get a lot of it that way.

**Comment by Zac-HD** [comment]
We could for at least most deprecations, but I think it would actually impose *greater* coordination costs than cleanly deleting everything at once.  Consider e.g. how we'd maintain our tests - either we'd have to drop the full coverage requirement for the duration, or else delete the tests all at once (and at that point why not finish the job?).

And while it will be a big diff, it's all really simple changes to make - and easy to review as commits too. My estimate is a day of editing for me and a few hours of review for each of you, nontrivial but not huge either.

**Comment by Zac-HD** [comment]
https://github.com/HypothesisWorks/hypothesis/compare/master...Zac-HD:v4-experiments is a partial diff from last time we tried this.  Unclear if it's going to be easier to resolve all the merge conflicts or just re-do the edits though!

**Comment by DRMacIver** [comment]
>  either we'd have to drop the full coverage requirement for the duration

No, this could easily be solved by disabling the error when running inside the `checks_deprecated_behaviour` decorators etc.

> And while it will be a big diff, it's all really simple changes to make -

Well the issue isn't making the changes, it's keeping them made.

**Comment by Zac-HD** [comment]
I'm putting the cutoff for removals at (or rather just after) [Hypothesis 3.66](https://hypothesis.readthedocs.io/en/latest/changes.html#v3-66-0), so we can tighten and simplify the validation for `text()`.

That was released on 5th July, and therefore puts our target release date six months later on the 5th of January.  Unless we manage to get 4.0 out this week (:rofl:), that's when I get back from my camping trip!

**Comment by Zac-HD** [comment]
My WIP branch is https://github.com/HypothesisWorks/hypothesis/compare/master...Zac-HD:v4-experiments
