### ISSUE TITLE
`from_type` should support the new things in Python 3.8

### ISSUE THREAD

**Issue by Zac-HD** [HypothesisWorks/hypothesis#2116]
- [x] (#2158) [`typing.SupportsIndex`](https://docs.python.org/3.8/library/typing.html#typing.SupportsIndex), a quick entry in our lookup table; 
- [x] (#2161) [`typing.Literal`](https://docs.python.org/3.8/library/typing.html#typing.Literal), get the value and wrap that in `st.just()`;
- [x] [`typing.Final`](https://docs.python.org/3.8/library/typing.html#typing.Final), get value and pass back to the outer `st.from_type()`; and
- [x] [`typing.TypedDict`](https://docs.python.org/3.8/library/typing.html#typing.TypedDict) which should be implemented in terms of #1913 with `st.just()` for the keys and `st.from_type()` for values.

This won't be particularly *hard*, just fiddly in getting it to work on 3.8 or when the `typing` backport has those types without breaking older versions at all.

**Comment by GrigoriosGiann** [comment]
Hello 👋!
I'd love to take this up 😄

**Comment by Zac-HD** [comment]
Per our usual reservation policy, this issue is all yours for the next week then!

I'd suggest a series of small PRs, or at least leaving TypedDict for a follow-up as it will be fairly fiddly. The others aren't too bad, it's mostly the version compatibility logic 🙂
