### ISSUE TITLE
Codemods to automatically upgrade for newer Hypothesis versions

### ISSUE THREAD

**Issue by Zac-HD** [HypothesisWorks/hypothesis#2705]
Hypothesis is a mature project with a stable API - but we do *occasionally* deprecate and eventually remove things.  It would be nice if we shipped tools to automatically refactor affected code, and [LibCST looks great for that](https://libcst.readthedocs.io/en/latest/)!

### Codemod ideas

Automatically fix deprecated code, to make updating Hypothesis easier:

- [x] [Converting positional to keyword arguments](https://hypothesis.readthedocs.io/en/latest/changes.html#v5-5-0)  (largest impact and therefore highest priority) (in #2712)
- [x] [Converting `min_magnitude=None` to `min_magnitude=0`](https://hypothesis.readthedocs.io/en/latest/changes.html#v5-14-0) (in #2712)
- [ ] [Updating provisional IP address string strategies to the new form](https://hypothesis.readthedocs.io/en/latest/changes.html#v5-3-0)
- [There were many removals in 5.0.0 which could be codemodded](https://hypothesis.readthedocs.io/en/latest/changes.html#v5-0-0) to support slow-updating teams
- If you're [still using 3.x](https://pepy.tech/project/hypothesis?versions=5.*&versions=4.*&versions=3.*) and codemods for [removals in 4.0.0](https://hypothesis.readthedocs.io/en/latest/changes.html#v4-0-0) would help you update, please let us know

And of course deprecations aren't the *only* possible use for a refactoring tool:

- [ ] Convert `assume()` calls on a single argument into `.filter()` calls on the relevant strategy
- [ ] Use logic like #2701 to suggest converting strategies from filtering to valid-by-construction
- [ ] Discard the `@st.composite` decorator for functions which could just return a strategy, because they have no dependencies between draws.
- *other ideas TBD, suggestions welcome*

### General notes

- I'd like to support this via both the LibCST and the Hypothesis CLI, for maximum flexibility and visibility
- We should ensure that deprecation messages suggest using the codemod if one is available, and add that to our development guide (along with "please add a codemod, or issue, if deprecating something")

**Comment by sobolevn** [comment]
Important note: `libcst` does not work with `python3.10+` and can break on some `python3.9` code.
Related https://github.com/Instagram/LibCST/issues/285

**Comment by Zac-HD** [comment]
I hope that they'll fix that soon!

In the meantime, I'm optimistic that this will be fairly low-impact - if you're running codemods, that implies you've been using Hypothesis for a while and can probably upgrade library versions before trying the Python version upgrade.  Even if some of your test files no longer compile under Python 3.9, using 3.8 to run `hypothesis codemod ...` will at least handle the others.

**Comment by Zac-HD** [comment]
Closing this because the remaining ideas don't seem worth the implementation effort; though I'd still be delighted to accept PRs if anyone would like to build more codemods 🙂
