### ISSUE TITLE
Merge the website into this repo

### ISSUE THREAD

**Issue by Zac-HD** [HypothesisWorks/hypothesis#2943]
We've intended since #1224 to *eventually* merge [the website](https://hypothesis.works/) into this repo, and between #2664 and https://github.com/HypothesisWorks/HypothesisWorks.github.io/pull/30 I think we should do so soon.  Points to consider:

- [x] Merge the website repo into a `/website/` directory in this one, [keeping the git history](https://stackoverflow.com/questions/1425892/how-do-you-merge-two-git-repositories)
      Done in #3333 by @Macavirus 🎉 
- [x] Fix any bit-rot in the build system so that builds work nicely
  - https://github.com/HypothesisWorks/hypothesis/compare/master...Zac-HD:website-revival throws out the old Jekyll build entirely to use Pelican (a pure-Python static site generator).  Needs a nice theme; otherwise done - including deleting obsolete product and training pages.
  - [ ] delete newsletter signup link https://github.com/HypothesisWorks/HypothesisWorks.github.io/issues/35
  - [x] delete reference to long-dead Java prototype https://github.com/HypothesisWorks/HypothesisWorks.github.io/issues/36
- [ ] Add a live-preview for pull requests so that we can check changes
- [x] Point 'production' to the new version (DNS?  GitHub Pages config?)
- [ ] Ensure that `hypothesis.works` and `hypothesis.readthedocs.org` prominently link to each other
  - [ ] Maybe we should host docs at `docs.hypothesis.works`?
- [ ] Write more blog posts, e.g. talking about the Ghostwriter or cool case studies
  - [ ] article on the "expected result for explicit examples" trick
    ```python
    unknown_result = object()
    
    @example(x=1, expected=2)
    @example(x=2, expected=unknown_result)
    @given(x=st.integers(), expected=st.just(unknown_result))
    def test(x, expected):
        result = f(x)
        assert 0 <= x  # whatever properties you want
        if expected is not unknown_result:
           assert result == expected  # if we know the exact output, assert that too!
    ```
  - [ ] article on ghostwriter argument-guessing (https://github.com/HypothesisWorks/hypothesis/pull/3313); complete with list and link to online demo https://zhd.dev/ghostwriter/
  - [ ] a "big list of properties" as recipes with Hypothesis, similar to [this F# post](https://fsharpforfunandprofit.com/posts/property-based-testing-2/)
  - [ ] update [Hypothesis article about fixtures interaction](https://hypothesis.works/articles/hypothesis-pytest-fixtures/) with respect to [this stackoverflow question](https://stackoverflow.com/questions/72792829/use-pytest-fixtures-in-test-with-hypothesis).

Doesn't need to be in that exact order, but I think those are the main points.
