### ISSUE TITLE
Signature of `given` is partially unknown for Python < 3.10

### ISSUE THREAD

**Issue by rsokl** [HypothesisWorks/hypothesis#3379]
(updated issue from https://github.com/HypothesisWorks/hypothesis/issues/3375 which misdiagnosed things as a pylance issue)

This is associated with the introduction of `InferType` in #3247 :

https://github.com/HypothesisWorks/hypothesis/blob/b73d6fd51d8dc31f23da1ad4bfdd9dc18401c3b8/hypothesis-python/src/hypothesis/core.py#L115-L119

As of their latest versions, mypy and pyright do not process `InferType = type(Ellipsis)` in a way that can be used in annotations.

```python
from hypothesis import given

@given(1)  # static type checkers should raise an error here
def f(x): 
    pass
```

**mypy:**

```console
$ mypy --version
mypy 0.961 (compiled: yes)

$ mypy scratch.py --python-version=3.9                                                                                                      
Success: no issues found in 1 source file

$ mypy scratch.py --python-version=3.10
scratch.py:3: error: No overload variant of "given" matches argument type "int"
scratch.py:3: note: Possible overload variants:
scratch.py:3: note:     def given(*_given_arguments: Union[SearchStrategy[Any], ellipsis]) -> Callable[[Callable[..., Optional[Coroutine[Any, Any, None]]]], Callable[..., None]]
scratch.py:3: note:     def given(**_given_kwargs: Union[SearchStrategy[Any], ellipsis]) -> Callable[[Callable[..., Optional[Coroutine[Any, 
Any, None]]]], Callable[..., None]]
Found 1 error in 1 file (checked 1 source file)
```
**pyright:**

```console
$ pyright --version
pyright 1.1.255

$ pyright scratch.py --pythonversion=3.9
Loading configuration file at C:\Users\Ryan Soklaski\hydra-zen\pyrightconfig.json
Assuming Python platform Windows
stubPath C:\Users\Ryan Soklaski\hydra-zen\typings is not a valid directory.
Searching for source files
Found 1 source file
pyright 1.1.255
0 errors, 0 warnings, 0 informations
Completed in 1.953sec

$ pyright scratch.py --pythonversion=3.10
Loading configuration file at C:\Users\Ryan Soklaski\hydra-zen\pyrightconfig.json
Assuming Python platform Windows
stubPath C:\Users\Ryan Soklaski\hydra-zen\typings is not a valid directory.
Searching for source files
Found 1 source file
pyright 1.1.255
C:\Users\Ryan Soklaski\hydra-zen\scratch\scratch.py
  C:\Users\Ryan Soklaski\hydra-zen\scratch\scratch.py:3:8 - error: Argument of type "Literal[1]" cannot be assigned to parameter "_given_arguments" of type "SearchStrategy[Any] | EllipsisType" in function "given"
    Type "Literal[1]" cannot be assigned to type "SearchStrategy[Any] | EllipsisType"
      "Literal[1]" is incompatible with "SearchStrategy[Any]"
      "Literal[1]" is incompatible with "EllipsisType" (reportGeneralTypeIssues)
1 error, 0 warnings, 0 informations
Completed in 1.857sec
```

Fortunately it seems like [there is a solution](https://github.com/PyCQA/pyflakes/issues/616#issuecomment-796311886) here, which is to rely on the implementation of `ellipsis` in `builtins.pyi`

```python
from typing import TYPE_CHECKING

import sys

if sys.version_info >= (3, 10):  # pragma: no cover 
    from types import EllipsisType as InferType 
elif TYPE_CHECKING: 
    from builtins import ellipsis as InferType
else:
    InferType = type(Ellipsis)
```

I tested this script:

```python
from typing import TYPE_CHECKING

import sys

if sys.version_info >= (3, 10):  # pragma: no cover 
    from types import EllipsisType as InferType 
elif TYPE_CHECKING: 
    from builtins import ellipsis as InferType
else:
    InferType = type(Ellipsis)

def t1(x: InferType):
    pass

t1(...)

t1(1)  # mypy and pyright both correctly raise errors here for Python 3.9 and 3.10
```

## To-Do:
- [x] Update `InferType` to the above definition
- [x] Add mypy & pyright tests for `given(1)(func)`
- [x] parameterize our mypy & pyright tests over python versions
