### ISSUE TITLE
🏃 Sprints meta-issue

### ISSUE THREAD

**Issue by Zac-HD** [HypothesisWorks/hypothesis#3402]
This weekend is [the SciPy 2022 sprints](https://www.scipy2022.scipy.org/sprints) (and [EuroPython sprints](https://ep2022.europython.eu/sprints)!); if you're keen to contribute to Hypothesis, apply Hypothesis to other sprinting projects, or work on some related issues, you're in the right place.  How this works:

1. Talk to Zac about which of the issues below you might work on, and we'll reserve it (check the box)
2. Fix the issue, make a PR, and iterate on it.
3. PR gets merged, celebrate!

### Hypothesis issues
- [x] [easy] `math.isfinite`, `isnan`, and `isinf` filter-rewriting from https://github.com/HypothesisWorks/hypothesis/issues/2701
- [x] [easy] Add `allow_subnormal=` param to the `complex_numbers()` strategy https://github.com/HypothesisWorks/hypothesis/issues/3390
- [x] [easy] Ensure warnings point to user code https://github.com/HypothesisWorks/hypothesis/issues/3403
- [x] [easy] Improve Ghostwriter CLI error message https://github.com/HypothesisWorks/hypothesis/issues/3404
- [ ] [easy] Numpy new prng support https://github.com/HypothesisWorks/hypothesis/issues/3131
- [x] [inter] Hit integer bounds more often https://github.com/HypothesisWorks/hypothesis/issues/2942
- [ ] [inter] Pandera efficiency issue https://github.com/pandera-dev/pandera/issues/404
- [x] [inter] AST-based warning for `@st.composite` misuse https://github.com/HypothesisWorks/hypothesis/issues/3384
- [ ] [inter] annotated-types constraint support: https://github.com/HypothesisWorks/hypothesis/issues/3356
- [ ] [inter] `from_type(np.typing.NDArray)` should work https://github.com/HypothesisWorks/hypothesis/issues/3150
- [ ] [inter] internal type annotations https://github.com/HypothesisWorks/hypothesis/issues/3074
- [ ] [inter] get the website build working in GitHub Actions https://github.com/HypothesisWorks/hypothesis/issues/2943
- [ ] [inter] structured timezones strategy https://github.com/HypothesisWorks/hypothesis/issues/2414

### Ecosystem issues
- [x] [easy] Clarify error message https://github.com/pytest-dev/pytest/issues/10113#issuecomment-1180482512
- [ ] [easy] Better exception chaining https://github.com/pytest-dev/pytest/issues/1904
- [ ] [easy] Support `staticmethod`s https://github.com/agronholm/typeguard/issues/231
- [ ] [easy] Improve dtype-in-array repr https://github.com/numpy/numpy/issues/19059
- [ ] [inter] Improve error message for structured arrays https://github.com/numpy/numpy/issues/14239
- [ ] [inter] matplotlib x/y axis inconsistency https://github.com/matplotlib/matplotlib/issues/11193
- [ ] [inter] Write property-based tests!
  - Numpy, Pandas, Dask, or any other interested packages
  - https://github.com/astropy/astropy/issues/9017
  - https://github.com/pydata/xarray/issues/1846
  - https://github.com/scikit-learn/scikit-learn/issues/13846
  - https://github.com/dask/dask-image/issues/208
  - https://github.com/napari/napari/issues/2444
  - https://github.com/qutip/qutip/pull/1957

**Comment by Zac-HD** [comment]
### If you're at EuroPython...

On Saturday, please choose one of the issues below, or one of the *intermediate* Hypothesis issues above.  We'd like to avoid conflicting or duplicate work without too much live coordination.  (On Sunday, pick anything 😁)

- [ ] [inter] Many more rewrite rules for shed https://github.com/Zac-HD/shed/issues/22
- [ ] [inter] Fix linter false-alarm https://github.com/PyCQA/flake8-bugbear/issues/269#issuecomment-1173446387
- [ ] [hard] Have `pytest.warns()` re-`showwarnings()` all unmatched warnings on context/call exit - see https://github.com/pytest-dev/pytest/issues/4905 and https://github.com/pytest-dev/pytest/issues/9288 and unfinished PR; check that this also fixes https://github.com/pytest-dev/pytest/issues/9036

**Comment by gzaxel** [comment]
I have found it interesting to work on #2414, I will need probably more time than one day for that ;)

**Comment by Zac-HD** [comment]
With the sprints over, it's time to close this meta-issue - until next time.  Thanks again to everyone who helped out here or in other projects, for your contribution and the fun we had together!
