### ISSUE TITLE
PyCon US 2024 sprints!

### ISSUE THREAD

**Issue by Zac-HD** [HypothesisWorks/hypothesis#3994]
<details>
<summary>I used up all the beginner and intermediate issues at the mentored sprints</summary>

Welcome to [the mentored sprints](https://us.pycon.org/2024/events/mentored-sprints/)!

- [x] https://github.com/annotated-types/annotated-types/issues/66 - fix docstring and type annotation
- [x] https://github.com/HypothesisWorks/hypothesis/issues/3993 - treat Unpack as GroupedMetadata
- [x] https://github.com/pandas-dev/pandas/issues/54979 - update Pandas changelog + docs
- [x] https://github.com/python-trio/trio/issues/1439 - small documentation fix in Trio
- [x] https://github.com/pytest-dev/pytest/issues/10478 - warn on unmatchable regex patterns

</details>

Experienced (<1 day)
- [ ] https://github.com/HypothesisWorks/hypothesis/issues/3985 - stack-depth of warning in @st.composite
- [ ] https://github.com/HypothesisWorks/hypothesis/issues/3947 - ghostwriter.magic(numpy.matmul) in py312
- [ ] https://github.com/HypothesisWorks/hypothesis/issues/3716 - fixing over-eager import of Django stuff

Experienced (~1 day)
- [ ] https://github.com/HypothesisWorks/hypothesis/issues/3944 - consumes(some_bundle).filter(...)
- [ ] https://github.com/HypothesisWorks/hypothesis/issues/3131 - strategy for numpy PRNGs (requires numpy familiarity)
- [ ] https://github.com/HypothesisWorks/hypothesis/issues/3074 - internal type annotations; could take several people
    - [ ] larger+harder extension: mypyc compilation?
- [ ] https://github.com/python-jsonschema/hypothesis-jsonschema/issues/106 - CLI for hypothesis-jsonschema (via Hypothesis plugin?  cf HypoFuzz)
- [ ] https://github.com/Zac-HD/shed/issues/49 - online interactive demo for shed 

Experienced (>1 day)
- [ ] https://github.com/HypothesisWorks/hypothesis/issues/3781 - using sys.monitoring for Scrutineer
- [ ] https://github.com/HypothesisWorks/hypothesis/issues/3551 - reporting improvements for Scrutineer
- [ ] https://github.com/HypothesisWorks/hypothesis/issues/2957 - structured docstrings; good technical writing project
- [ ] https://github.com/python-jsonschema/hypothesis-jsonschema/issues/104 - rebuild schema canonicalization (but better)
- [ ] https://github.com/ipython/ipyparallel/issues/814 - transition to ExceptionGroup

Expert
- [ ] https://github.com/HypothesisWorks/hypothesis/issues/3914 - stabilizing the z3 backend
- [ ] https://github.com/HypothesisWorks/hypothesis/issues/3176 - when to optimize targets?
- [ ] https://github.com/python-jsonschema/hypothesis-jsonschema/issues/85 - converting js regex patterns to python, and merging patterns

**Comment by nillsscb** [comment]
I, Niels Burmester, with Andrea Mock, will work on https://github.com/pandas-dev/pandas/issues/54979 (Build: pandas 2.1.0 has no win32 wheels)

**Comment by oakal510** [comment]
I will work on the trio token issue.

**Comment by Zac-HD** [comment]
Closing this as the sprints are winding down - we ended up applying Hypothesis to other projects, since that benefits more from in-personal collaboration than the issues above 🙂
