### ISSUE TITLE
Hypothesis build rationalization parent ticket

### ISSUE THREAD

**Issue by DRMacIver** [HypothesisWorks/hypothesis#570]
As the recent build wrangling demonstrated, there's an *awful* lot of time and effort that's gone into the Hypothesis build, and approximately zero% of it is anything Hypothesis specific (except in the sense that Hypothesis specifically has a creator who is really pedantic about software quality). It's almost all stuff that literally every Python project could benefit from but very few bother with because it's hard.

It's also a tangled mess, which isn't doing us any favours.

I'd like to start looking into carving out key bits of it and trying to make them useful to other projects, even if only so *I* can use them on other projects. This will require a bunch of cleanup and should definitely be done incrementally.

Here are the immediate things I think should be factored out:

* [ ] The snakepit, our somewhat idiosyncratic approach to managing pythons for install, is actually really really useful. It's awful codewise, and has a lot of things that annoy people about it. I'd like to tidy it up, improve its functionality, and move it into its own project. There is already [a package on pypi](http://pypi.python.org/pypi/snakepit) so this will require a rename.
* [ ] The recent deploy stuff. I can't imagine many people are actually using the existing Travis deployment, but having this sort of deploy automation is really nice. This will also make @froztbyte happy because it will force me to move all the magic strings into configuration. :-) I think this should wait a bit for it to stabilise (e.g. we're still finding things like #564)

Here are my *long-term* highly aspirational goals for this though:

* [x] Get rid of the Makefile and replace it with a Python program
* [x] Remove as much shell from the system as humanly possible. Shell should be there only to bootstrap us to enough Python to run the rest.
* [ ] Have the build work natively on Windows.
* [ ] Have as little per CI config as possible (and where necessary do it in code).
* [ ] Create a small CLI wizard that just asks you some basic questions and then gives you something as close to the Hypothesis build as generically possible. Ideally with most of the basic questions library-ized rather than templates so that it's easy to update to new versions.

**Comment by Zac-HD** [comment]
Re: long-term goals, we could create a [cookiecutter template](https://github.com/audreyr/cookiecutter) for the bits that don't make sense as independent packages.

**Comment by Zac-HD** [comment]
I think we've basically stabilised our build system in the `hypothesistooling` project (the `tooling/` directory), so I'm going to close this as somewhere between "fixed" and "wontfix".
